import os
import ast
import pandas as pd
from pymongo import MongoClient
from dotenv import load_dotenv

# Load environment variables (e.g., MONGODB_URI)
load_dotenv()

def connect_db():
    """
    Connect to MongoDB using the URI in the environment variables.
    Returns the 'ai_recruiter' database object.
    
    Schema Design Summary:
    1. 'candidates' Collection:
       - _id: ObjectId
       - name: String
       - email: String
       - skills: Array of Strings
       - experience_years: Int
       - education: Array of subdocuments {degree, institution, year}
       - past_roles: Array of subdocuments {title, company, duration_years, description}
       - certifications: Array of Strings
       - projects: Array of subdocuments {title, description, tech_stack}
       - location: String
       - open_to_relocation: Bool
       - raw_resume_text: String (Auto-generated by concatenating other fields)
       
    2. 'candidate_behavior' Collection:
       - _id: ObjectId
       - candidate_id: ObjectId (Reference to candidates._id)
       - last_active_date: Date/String
       - profile_updated_date: Date/String
       - applications_last_30_days: Int
       - interview_response_rate: Float (0-1)
       - profile_completeness: Float (0-1)
       - courses_completed: Array of Strings
       - login_frequency_per_week: Float
    """
    uri = os.getenv("MONGODB_URI", "mongodb://localhost:27017/")
    client = MongoClient(uri)
    db = client["ai_recruiter"]
    return db

def build_resume_text(candidate_doc):
    """
    Concatenates skills, past_roles descriptions, projects, certifications, 
    and education into one clean text blob.
    """
    parts = []
    
    # Skills
    if candidate_doc.get('skills'):
        skills = candidate_doc['skills']
        if isinstance(skills, list):
            parts.append("Skills: " + ", ".join(skills))
            
    # Past Roles
    if candidate_doc.get('past_roles'):
        roles = candidate_doc['past_roles']
        if isinstance(roles, list):
            roles_text = []
            for r in roles:
                title = r.get('title', '')
                company = r.get('company', '')
                desc = r.get('description', '')
                roles_text.append(f"{title} at {company}: {desc}")
            if roles_text:
                parts.append("Experience:\n" + "\n".join(roles_text))
                
    # Projects
    if candidate_doc.get('projects'):
        projects = candidate_doc['projects']
        if isinstance(projects, list):
            proj_text = []
            for p in projects:
                title = p.get('title', '')
                desc = p.get('description', '')
                tech = p.get('tech_stack', [])
                tech_str = ", ".join(tech) if isinstance(tech, list) else str(tech)
                proj_text.append(f"{title} (Tech: {tech_str}): {desc}")
            if proj_text:
                parts.append("Projects:\n" + "\n".join(proj_text))
                
    # Certifications
    if candidate_doc.get('certifications'):
        certs = candidate_doc['certifications']
        if isinstance(certs, list):
            parts.append("Certifications: " + ", ".join(certs))
            
    # Education
    if candidate_doc.get('education'):
        edu = candidate_doc['education']
        if isinstance(edu, list):
            edu_text = []
            for e in edu:
                degree = e.get('degree', '')
                inst = e.get('institution', '')
                year = e.get('year', '')
                edu_text.append(f"{degree} from {inst} ({year})")
            if edu_text:
                parts.append("Education:\n" + "\n".join(edu_text))
                
    return "\n\n".join(parts)

def _clean_value(val):
    if pd.isna(val):
        return None
    if isinstance(val, str):
        val = val.strip()
        if not val:
            return None
        # Attempt to parse stringified JSON/lists (e.g., "['Python', 'Java']")
        if (val.startswith('[') and val.endswith(']')) or (val.startswith('{') and val.endswith('}')):
            try:
                return ast.literal_eval(val)
            except (ValueError, SyntaxError):
                pass
    return val

def ingest_csv_to_mongo(csv_path, collection_name):
    """
    Loads raw CSV/JSON dataset with pandas, cleans nulls/whitespace, 
    and inserts into the appropriate MongoDB collection.
    """
    print(f"Loading data from {csv_path} into collection '{collection_name}'...")
    
    if csv_path.endswith('.csv'):
        df = pd.read_csv(csv_path)
    elif csv_path.endswith('.json'):
        df = pd.read_json(csv_path)
    else:
        raise ValueError("Unsupported file format. Please use .csv or .json")
        
    db = connect_db()
    collection = db[collection_name]
    
    docs = []
    missing_stats = {col: 0 for col in df.columns}
    total_rows = len(df)
    
    for _, row in df.iterrows():
        doc = {}
        for col in df.columns:
            val = _clean_value(row[col])
            doc[col] = val
            if val is None:
                missing_stats[col] += 1
                
        # Generate raw_resume_text for candidates
        if collection_name == "candidates":
            doc['raw_resume_text'] = build_resume_text(doc)
            
        docs.append(doc)
        
    if docs:
        # Clear collection for fresh ingestion or just insert? Usually insert. 
        # But for seed script, let's just insert.
        collection.insert_many(docs)
        print(f"Successfully inserted {len(docs)} documents.")
        
    print(f"\n=== Ingestion Summary for '{collection_name}' ===")
    print(f"Total records processed: {total_rows}")
    print("Missing fields percentage:")
    for col, count in missing_stats.items():
        pct = (count / total_rows) * 100 if total_rows > 0 else 0
        print(f"  - {col}: {pct:.1f}% ({count} missing)")
    print("===================================================\n")

if __name__ == "__main__":
    # Example usage (uncomment when data is ready):
    # ingest_csv_to_mongo("../data/candidates_raw.csv", "candidates")
    # ingest_csv_to_mongo("../data/behavior_raw.csv", "candidate_behavior")
    pass
